file_format: "1"
id: eyeslash_sofle
name: Eyeslash Sofle
url: https://github.com/a741725193/zmk-sofle
type: shield
requires: [pro_micro]
features:
  - keys
  - display
outputs:
  - usb
  - ble
siblings:
  - eyeslash_sofle_left
  - eyeslash_sofle_right